"use client"

import type React from "react"

import { useState } from "react"
import { userService } from "@/lib/firebase-services"
import { binaryTreeService } from "@/lib/binary-tree-service"
import { useAuthStore } from "@/store/authStore"
import { toast } from "react-hot-toast"

interface RegistrationFormProps {
  onSuccess?: () => void
}

export function UserRegistrationForm({ onSuccess }: RegistrationFormProps) {
  const { user: adminUser } = useAuthStore()
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    email: "",
    firstName: "",
    lastName: "",
    phone: "",
    sponsorId: "",
    packageId: "",
    placementSide: "" as "left" | "right" | "",
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!adminUser?.companyId) {
      toast.error("Company ID not found")
      return
    }

    try {
      setLoading(true)

      // Validate required fields
      if (!formData.email || !formData.firstName || !formData.lastName || !formData.packageId) {
        toast.error("Please fill in all required fields")
        return
      }

      // Create user
      const userId = await userService.create(adminUser.companyId, {
        id: "", // Will be generated by Firestore
        companyId: adminUser.companyId,
        email: formData.email,
        firstName: formData.firstName,
        lastName: formData.lastName,
        phone: formData.phone,
        sponsorId: formData.sponsorId || undefined,
        packageId: formData.packageId,
        status: "active",
        kycStatus: "pending",
        blockedIncome: false,
        blockedWithdrawals: false,
        placementSide: formData.placementSide || undefined,
      } as any)

      // Create binary position
      await binaryTreeService.createBinaryPosition(adminUser.companyId, userId, formData.placementSide as any)

      // If sponsor provided, place user in sponsor's tree
      if (formData.sponsorId && formData.placementSide) {
        await binaryTreeService.placeUser(
          adminUser.companyId,
          userId,
          formData.sponsorId,
          formData.placementSide as "left" | "right",
        )
      }

      toast.success("User registered successfully")
      setFormData({
        email: "",
        firstName: "",
        lastName: "",
        phone: "",
        sponsorId: "",
        packageId: "",
        placementSide: "",
      })
      onSuccess?.()
    } catch (error: any) {
      console.error("[v0] Registration error:", error)
      toast.error(error.message || "Failed to register user")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
      <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Register New User</h3>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">First Name *</label>
            <input
              type="text"
              required
              value={formData.firstName}
              onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Last Name *</label>
            <input
              type="text"
              required
              value={formData.lastName}
              onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Email *</label>
          <input
            type="email"
            required
            value={formData.email}
            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Phone</label>
          <input
            type="tel"
            value={formData.phone}
            onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
          />
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Sponsor ID</label>
            <input
              type="text"
              value={formData.sponsorId}
              onChange={(e) => setFormData({ ...formData, sponsorId: e.target.value })}
              placeholder="Optional"
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Placement Side</label>
            <select
              value={formData.placementSide}
              onChange={(e) => setFormData({ ...formData, placementSide: e.target.value as any })}
              className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
            >
              <option value="">Select Side</option>
              <option value="left">Left</option>
              <option value="right">Right</option>
            </select>
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Package *</label>
          <input
            type="text"
            required
            value={formData.packageId}
            onChange={(e) => setFormData({ ...formData, packageId: e.target.value })}
            placeholder="Package ID or name"
            className="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md dark:bg-gray-700 dark:border-gray-600 dark:text-white"
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:bg-gray-400"
        >
          {loading ? "Registering..." : "Register User"}
        </button>
      </form>
    </div>
  )
}
